"""additional ids on storage model

Revision ID: b51045d26d1f
Revises: 
Create Date: 2023-10-15 19:09:53.283215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51045d26d1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('file_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('user_fk', sa.BigInteger(), nullable=False),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_storage')
    op.drop_table('users')
    # ### end Alembic commands ###
