"""empty message

Revision ID: d17052ed4bb5
Revises: 
Create Date: 2024-01-31 11:16:57.599706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d17052ed4bb5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orioks_groups",
        sa.Column("group_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("group_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "file_storage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("user_fk", sa.BigInteger(), nullable=False),
        sa.Column("time_create", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id", "file_id"),
    )
    op.create_table(
        "orioks_students",
        sa.Column("student_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_fk", sa.String(), nullable=True),
        sa.Column("user_fk", sa.BigInteger(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("time_create", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_fk"],
            ["orioks_groups.group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("student_id"),
    )
    op.create_table(
        "reminders",
        sa.Column("reminder_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("reminder_type", sa.String(), nullable=False),
        sa.Column("reminder_desc", sa.String(), nullable=False),
        sa.Column("user_fk", sa.BigInteger(), nullable=False),
        sa.Column("time_create", sa.DateTime(), nullable=True),
        sa.Column("time_triggers", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_fk"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("reminder_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminders")
    op.drop_table("orioks_students")
    op.drop_table("file_storage")
    op.drop_table("users")
    op.drop_table("orioks_groups")
    # ### end Alembic commands ###
