"""orioks models added

Revision ID: fbb779229134
Revises: 8ee3691f6255
Create Date: 2023-10-18 18:38:01.637613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb779229134'
down_revision: Union[str, None] = '8ee3691f6255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orioks_groups',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('orioks_students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_fk', sa.String(), nullable=True),
    sa.Column('user_fk', sa.BigInteger(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('time_create', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_fk'], ['orioks_groups.group_id'], ),
    sa.ForeignKeyConstraint(['user_fk'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orioks_students')
    op.drop_table('orioks_groups')
    # ### end Alembic commands ###
